---
- name:  "install samba"
  hosts: xyz
  remote_user: root
  tasks:
  - name: "Ensure package is latest"
    ansible.builtin.yum:
      name: samba
      state: present 
  - name: "copying the configuration files"
    ansible.builtin.template:
      src: templates/group
      dest:  /tmp/ 
